---
name: checking # this string appears on badge
on:
  - push
  - pull_request
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install xsltproc
        run: sudo apt-get install -y xsltproc
      - name: Looking around
        run: |
          echo '::group::pwd'
          pwd
          echo '::endgroup::'
          echo '::group::ls'
          ls -al
          echo '::endgroup::'
          echo '::group::xsltproc version'
          xsltproc --version
          echo '::endgroup::'
          echo '::group::make version'
          make --version
          echo '::endgroup::'
      - name: Checking
        run: make ci
